- name: Remove old WP files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/fail2ban/filter.d/wordpress.conf
    - /etc/fail2ban/jail.d/wordpress.conf
  notify: restart fail2ban

- name: Install the filters
  copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/filter.d/
  with_fileglob:
      - files/filters/*
  notify: restart fail2ban

- name: Install the jails
  copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d/
  with_fileglob:
      - files/jails/*
  notify: restart fail2ban

- name: Install the greenlist
  ansible.builtin.template:
    src: templates/jails/greenlist.conf.j2
    dest: /etc/fail2ban/jail.d/greenlist.conf
  notify: restart fail2ban
